---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: iamsauravsharma/create-dotenv@v2.0.1
        with:
          file-path: '/tmp/.env'
        env:
          GITHUB_TOKEN: ${{ secrets.STUDIO_GITHUB_TOKEN }}
      - uses: cliffano/command-docker-action@main
        with:
          command: 'make ci'
          image: cliffano/studio
          shell: bash
          env_file: '/tmp/.env'
