---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - uses: iamsauravsharma/create-dotenv@v2.0.1
        with:
          file-path: '/tmp/.env'
        env:
          GITHUB_TOKEN: ${{ secrets.KONTIKI818_GITHUB_TOKEN }}
      - uses: cliffano/command-docker-action@v2.0.0
        with:
          command: 'make ci'
          image: cliffano/kon-tiki
          shell: bash
          env_file: '/tmp/.env'
          # based on https://github.com/cliffano/packer-kon-tiki/blob/main/provisioners/shell/info-post.sh#L5C13-L5C80
          # TODO: replace /root with kon-tiki-user's home when available
          extra_path: '/root/.local/bin:/root/go/bin:/usr/local/go/bin:/usr/local/node/bin'
